"""supply_settings add column short_name

Revision ID: b216be76f6f5
Revises: 2bd2d8fe6b15
Create Date: 2025-10-14 13:18:21.995278

"""

import sqlalchemy as sa
from alembic import op
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b216be76f6f5"
down_revision: Union[str, None] = "2bd2d8fe6b15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("supply_settings", sa.Column("short_name", sa.String()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supply_settings", "short_name")
